// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_w0IPpOoIiOalDXv_hh--dRRYS9dOlSQ',
    appId: '1:167248948966:web:61ba1d296bb5b1611f1527',
    messagingSenderId: '167248948966',
    projectId: 'triangulum-c55f1',
    authDomain: 'triangulum-c55f1.firebaseapp.com',
    storageBucket: 'triangulum-c55f1.firebasestorage.app',
    measurementId: 'G-4JTVQGFVXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAweLBJwL9axmSNR3fmCbxMM4LSOCod0uU',
    appId: '1:167248948966:android:7c79632657b85ea21f1527',
    messagingSenderId: '167248948966',
    projectId: 'triangulum-c55f1',
    storageBucket: 'triangulum-c55f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvvVN4Zy_DGeRq9aTYRsZCiedUKx6Zh24',
    appId: '1:167248948966:ios:f7cb0c5bc39a37bf1f1527',
    messagingSenderId: '167248948966',
    projectId: 'triangulum-c55f1',
    storageBucket: 'triangulum-c55f1.firebasestorage.app',
    iosClientId: '167248948966-q5suqad8t9ssqo3vo2h7sc43dde22pkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.triangulum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvvVN4Zy_DGeRq9aTYRsZCiedUKx6Zh24',
    appId: '1:167248948966:ios:f7cb0c5bc39a37bf1f1527',
    messagingSenderId: '167248948966',
    projectId: 'triangulum-c55f1',
    storageBucket: 'triangulum-c55f1.firebasestorage.app',
    iosClientId: '167248948966-q5suqad8t9ssqo3vo2h7sc43dde22pkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.triangulum',
  );
}
